# Generated by Django 4.1.5 on 2023-01-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="conference",
            field=models.CharField(
                choices=[("AFC", "AFC"), ("NFC", "NFC")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="division",
            field=models.CharField(
                choices=[
                    ("NORTH", "North"),
                    ("SOUTH", "South"),
                    ("EAST", "East"),
                    ("WEST", "West"),
                ],
                max_length=5,
            ),
        ),
    ]
