# Generated by Django 4.1.5 on 2023-01-30 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_team_conference_alter_team_division"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="players.position"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="players.team"
            ),
        ),
    ]
