# Generated by Django 4.1.5 on 2023-02-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0004_team_abbreviation"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="drafted",
            field=models.PositiveIntegerField(default=2022, max_length=4),
        ),
    ]
