# Generated by Django 4.1.5 on 2023-02-01 17:14

from django.db import migrations, models
import players.validators


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0005_player_drafted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="drafted",
            field=models.PositiveIntegerField(
                default=2022, validators=[players.validators.validate_draft_year]
            ),
        ),
    ]
